import type { Metadata } from "next";
import { Open_Sans, Poppins } from "next/font/google";
import Image from "next/image";

import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Huddle Landing Page App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${openSans.variable} relative bg-[#684BB1] antialiased`}
      >
        <div className="relative z-50 mx-auto min-h-screen px-6 sm:max-w-xl md:max-w-2xl md:px-10 lg:max-w-3xl lg:px-12 xl:max-w-6xl xl:px-12">
          {children}
        </div>
        <div>
          <Image
            src="/bg-mobile.svg"
            alt="Illustration Mockups"
            width={375}
            height={375}
            className="absolute inset-x-0 top-0 z-10 w-full bg-cover bg-center bg-no-repeat lg:hidden"
          />
          <Image
            src="/bg-desktop.svg"
            alt="Illustration Mockups"
            width={1318}
            height={800}
            className="absolute inset-x-0 top-0 z-10 hidden w-full bg-cover bg-center bg-no-repeat lg:block"
          />
        </div>
      </body>
    </html>
  );
}
